spring.datasource.url=jdbc:mysql://localhost:3308/studyroommate?useUnicode=true&characterEncoding=UTF-8&connectionTimeZone=Asia/Seoul
spring.datasource.username=ureca
spring.datasource.password=ureca

spring.jpa.hibernate.ddl-auto=update